[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true

[programs.localnet]
qubee_guard = "11111111111111111111111111111111"

[programs.devnet]
qubee_guard = "11111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "/keys/deployer.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
