[package]
name = "qubee-guard"
version = "0.1.0"
description = "QUBEE Solana Guard: a Token-2022 transfer hook that enforces QUBEE threat state"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "qubee_guard"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "1.0.2"
anchor-spl = "1.0.2"
spl-discriminator = "0.5"
spl-tlv-account-resolution = "0.11"
spl-transfer-hook-interface = "2"
