// Generates packages/shared/src/abi.ts from contracts/out (run after `forge build`).
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..', '..', '..')
const out = join(root, 'contracts', 'out')
const names = [
  'QuorumReceiver',
  'QuorumVault',
  'ColdVault',
  'RequestBoard',
  'KeyRegistry',
  'DepositVault',
  'ThreatRegistry',
  'QuorumLens',
  'ConfigTimelock',
  'OfficerSet',
  'Faucet',
  'MockERC20',
  'MockV3Aggregator',
  'DecoyCommit',
  'PatrolState',
  'OfficerDesk',
]

let src = '// Code generated by scripts/gen-abi.ts from contracts/out. Do not edit.\n\n'
for (const n of names) {
  const j = JSON.parse(readFileSync(join(out, `${n}.sol`, `${n}.json`), 'utf8'))
  src += `export const ${n}Abi = ${JSON.stringify(j.abi)} as const\n\n`
}
writeFileSync(join(import.meta.dir, '..', 'src', 'abi.ts'), src)
console.log(`wrote abi.ts (${names.length} contracts)`)
